addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: a0615448-cd63-4b70-a708-7324a8290302
after_failure: {}
after_success:
- ./df-build.sh
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications: {}
script: gradlew check
sudo: 'false'
# Modified by Insights Service at 2016-05-31 11:41:03.990935
