addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: a1171efe-6233-4035-84cb-fbaa07e6c707
after_success:
- ./df-build.sh
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications: {}
script: gradlew check
sudo: 'false'
# Modified by Insights Service at 2016-05-27 12:31:40.594859
